services:
  web:
    image: ubuntu/nginx # imagen de Nginx
    container_name: nginx_server # nombre del contenedor
    ports:
      - "8086:80" # mapeo de puertos  HTTP
      - "443:443"
    volumes:
      - ./sites-available:/etc/nginx/sites-available
      - ./website:/var/www/html/
      - ./scripts:/docker-entrypoint.d/
      - ./htpasswd/.htpasswd:/etc/nginx/.htpasswd
      - ./certs:/etc/nginx/certs
    restart: always